name = Catppuccin Mocha
kind = dark

bg             = #1e1e2e
fg             = #cdd6f4
accent         = #89b4fa
panel          = #181825
border         = #11111b
selection      = #45475a
line_highlight = #2a2b3c
line_number    = #585b70
cursor         = #f5e0dc
error          = #f38ba8
warning        = #f9e2af
success        = #a6e3a1

[syntax]
keyword        = #cba6f7
type           = #f9e2af
function       = #89b4fa
string         = #a6e3a1
number         = #fab387
comment        = #6c7086
constant       = #fab387
operator       = #89dceb
punctuation    = #9399b2
preproc        = #f5c2e7
builtin        = #f38ba8
attribute      = #f9e2af
tag            = #cba6f7
heading        = #f38ba8
escape         = #f5c2e7
