name = Ethereal
kind = dark

bg                 = #060b1e
fg                 = #ffcead
accent             = #7d82d9
panel              = #040816
border             = #030610
selection          = #252e56
line_highlight     = #121525
line_number        = #6d7db6
line_number_active = #ffcead
cursor             = #ffcead
error              = #ed5b5a
warning            = #e9bb4f
success            = #92a593

[syntax]
text        = #ffcead
keyword     = #ead7e7
type        = #e9bb4f
function    = #7d82d9
string      = #92a593
number      = #eb8b54
comment     = #6d7db6
constant    = #f7dc9c
operator    = #ffcead
punctuation = #836d66
preproc     = #a3bfd1
variable    = #ffcead
builtin     = #a3bfd1
attribute   = #a3bfd1
tag         = #e9bb4f
heading     = #7d82d9
inserted    = #92a593
deleted     = #ed5b5a
escape      = #ead7e7
link        = #7d82d9

[terminal]
black          = #060b1e
red            = #ed5b5a
green          = #92a593
yellow         = #e9bb4f
blue           = #7d82d9
magenta        = #c89dc1
cyan           = #a3bfd1
white          = #ffcead
bright_black   = #6d7db6
bright_red     = #faaaa9
bright_green   = #c4cfc4
bright_yellow  = #f7dc9c
bright_blue    = #c2c4f0
bright_magenta = #ead7e7
bright_cyan    = #dfeaf0
bright_white   = #ffcead
