name = Gruvbox Dark
kind = dark

bg             = #282828
fg             = #ebdbb2
accent         = #83a598
panel          = #1d2021
border         = #141617
selection      = #504945
line_highlight = #32302f
line_number    = #7c6f64
cursor         = #ebdbb2
error          = #fb4934
warning        = #fabd2f
success        = #b8bb26

[syntax]
keyword        = #fb4934
type           = #fabd2f
function       = #8ec07c
string         = #b8bb26
number         = #d3869b
comment        = #928374
constant       = #d3869b
operator       = #fe8019
punctuation    = #a89984
preproc        = #8ec07c
builtin        = #fe8019
attribute      = #fabd2f
tag            = #fb4934
heading        = #fabd2f
escape         = #fe8019
