name = Gruvbox Dark
kind = dark

bg             = #282828
fg             = #ebdbb2
accent         = #83a598
panel          = #1d2021
border         = #141617
selection      = #504945
line_highlight = #32302f
line_number    = #7c6f64
cursor         = #ebdbb2
error          = #fb4934
warning        = #fabd2f
success        = #b8bb26

[syntax]
keyword        = #fb4934
type           = #fabd2f
function       = #8ec07c
string         = #b8bb26
number         = #d3869b
comment        = #928374
constant       = #d3869b
operator       = #fe8019
punctuation    = #a89984
preproc        = #8ec07c
builtin        = #fe8019
attribute      = #fabd2f
tag            = #fb4934
heading        = #fabd2f
escape         = #fe8019

[terminal]
black          = #282828
red            = #ea6962
green          = #a9b665
yellow         = #d8a657
blue           = #7daea3
magenta        = #d3869b
cyan           = #89b482
white          = #d4be98
bright_black   = #665c54
bright_red     = #ea6962
bright_green   = #a9b665
bright_yellow  = #d8a657
bright_blue    = #7daea3
bright_magenta = #d3869b
bright_cyan    = #89b482
bright_white   = #d4be98
