name = Kanagawa
kind = dark

bg                 = #1f1f28
fg                 = #dcd7ba
accent             = #dcd7ba
panel              = #17171e
border             = #111116
selection          = #363646
line_highlight     = #2a2a37
line_number        = #54546d
line_number_active = #dcd7ba
cursor             = #dcd7ba
error              = #c34043
warning            = #c0a36e
success            = #76946a

[syntax]
text        = #dcd7ba
keyword     = #957fb8
type        = #7aa89f
function    = #7e9cd8
string      = #98bb6c
number      = #d27e99
comment     = #727169
constant    = #ffa066
operator    = #c0a36e
punctuation = #9cabca
preproc     = #e46876
variable    = #dcd7ba
builtin     = #7fb4ca
attribute   = #ffa066
tag         = #7fb4ca
heading     = #7e9cd8
inserted    = #76946a
deleted     = #c34043
escape      = #c0a36e
link        = #7fb4ca
