name = Miasma
kind = dark

bg                 = #222222
fg                 = #c2c2b0
accent             = #78824b
panel              = #191919
border             = #121212
selection          = #383838
line_highlight     = #2a2a29
line_number        = #666666
line_number_active = #c2c2b0
cursor             = #c2c2b0
error              = #685742
warning            = #b36d43
success            = #5f875f

[syntax]
text        = #c2c2b0
keyword     = #bb7744
type        = #b36d43
function    = #78824b
string      = #5f875f
number      = #8d6242
comment     = #666666
constant    = #b36d43
operator    = #c2c2b0
punctuation = #727269
preproc     = #c9a554
variable    = #c2c2b0
builtin     = #c9a554
attribute   = #c9a554
tag         = #b36d43
heading     = #78824b
inserted    = #5f875f
deleted     = #685742
escape      = #bb7744
link        = #78824b

[terminal]
black          = #222222
red            = #685742
green          = #5f875f
yellow         = #b36d43
blue           = #78824b
magenta        = #bb7744
cyan           = #c9a554
white          = #c2c2b0
bright_black   = #666666
bright_red     = #685742
bright_green   = #5f875f
bright_yellow  = #b36d43
bright_blue    = #78824b
bright_magenta = #bb7744
bright_cyan    = #c9a554
bright_white   = #c2c2b0
