name = Solarized Light
kind = light

bg             = #fdf6e3
fg             = #657b83
accent         = #268bd2
panel          = #eee8d5
border         = #ddd6c1
selection      = #e3dcc6
line_highlight = #f5efdc
line_number    = #93a1a1
cursor         = #586e75
error          = #dc322f
warning        = #b58900
success        = #859900

[syntax]
keyword        = #859900
type           = #b58900
function       = #268bd2
string         = #2aa198
number         = #d33682
comment        = #93a1a1
constant       = #cb4b16
operator       = #859900
punctuation    = #657b83
preproc        = #cb4b16
builtin        = #268bd2
attribute      = #b58900
tag            = #268bd2
heading        = #cb4b16
escape         = #dc322f
