name = Solitude
kind = dark

bg                 = #101315
fg                 = #cacccc
accent             = #798186
panel              = #0c0e10
border             = #080a0b
selection          = #343d41
line_highlight     = #1a1d1f
line_number        = #4b4e55
line_number_active = #cacccc
cursor             = #a5aeb4
error              = #565d60
warning            = #d9dbdc
success            = #9fa5a9

[syntax]
text        = #b4b4b4
keyword     = #b14242
type        = #d5d5d5
function    = #e5e5e5
string      = #df6464
number      = #4a8b8b
comment     = #737373
constant    = #c4693d
operator    = #d87c4a
punctuation = #737373
preproc     = #b14242
variable    = #b4b4b4
builtin     = #4a8b8b
attribute   = #949494
tag         = #949494
heading     = #b14242
inserted    = #629c7d
deleted     = #c53030
escape      = #d5d5d5
link        = #6e91c4
