name = Tokyo Night
kind = dark

bg             = #1a1b26
fg             = #c0caf5
accent         = #7aa2f7
panel          = #16161e
border         = #101014
selection      = #283457
line_highlight = #1e2030
line_number    = #3b4261
cursor         = #c0caf5
error          = #f7768e
warning        = #e0af68
success        = #9ece6a

[syntax]
keyword        = #bb9af7
type           = #2ac3de
function       = #7aa2f7
string         = #9ece6a
number         = #ff9e64
comment        = #565f89
constant       = #ff9e64
operator       = #89ddff
punctuation    = #a9b1d6
preproc        = #7dcfff
builtin        = #2ac3de
attribute      = #e0af68
tag            = #f7768e
heading        = #7aa2f7
escape         = #89ddff
