#!/usr/bin/env python3
"""Writes src/casefold.s: the simple case folding of every character whose folded form has as many
UTF-8 bytes as itself, for case-insensitive find (a match then has the needle's byte length).
usage: tools/casefold.py > src/casefold.s"""
import sys
import unicodedata


def fold(c):
    for f in (c.casefold(), c.lower()):
        if len(f) == 1:
            return f
    return c


def main():
    folds = {}
    for cp in range(0x80, 0x110000):
        c = chr(cp)
        if 0xD800 <= cp < 0xE000:
            continue
        f = fold(c)
        if f != c and len(f.encode()) == len(c.encode()):
            folds[cp] = ord(f)
    # an equivalence: folding a folded character changes nothing
    for cp, f in folds.items():
        assert folds.get(f, f) == f, hex(cp)
    # ranges: [lo, hi, delta, alternate], where an alternate range folds lo, lo + 2, ... and keeps the
    # characters between them
    ranges = []
    for cp in sorted(folds):
        delta = folds[cp] - cp
        if ranges:
            r = ranges[-1]
            if not r[3] and cp == r[1] + 1 and delta == r[2]:
                r[1] = cp
                continue
            if delta == 1 == r[2] and cp == r[1] + 2 and r[1] + 1 not in folds and (r[3] or r[0] == r[1]):
                r[1] = cp
                r[3] = 1
                continue
        ranges.append([cp, cp, delta, 0])
    out = sys.stdout
    out.write('# Generated by tools/casefold.py from Unicode %s; do not edit.\n' % unicodedata.unidata_version)
    out.write('# case_fold(cp) -> eax: the simple case folding of cp when it keeps its UTF-8 length, else cp\n')
    out.write('# (uses rax, rcx, rdx, r8-r10); fold_variants(cp) lists what folds to cp\n')
    out.write(CODE)
    out.write('.section .rodata\n.p2align 2\n# lo, hi, delta, 1 when only lo, lo + 2, ... fold\nfold_table:\n')
    for lo, hi, delta, alt in ranges:
        out.write('    .long 0x%x, 0x%x, %d, %d\n' % (lo, hi, delta, alt))
    out.write('fold_table_end:\n')


CODE = '''.include "rhun.inc"

.text
FN case_fold
    mov eax, edi
    cmp edi, 0x80
    jae 1f
    lea ecx, [rdi - 'A']
    cmp ecx, 25
    ja 9f
    or eax, 0x20
9:  ret
    # the first range ending at or after cp
1:  lea r8, [rip + fold_table]
    lea rdx, [rip + fold_table_end]
    sub rdx, r8
    shr edx, 4
    xor ecx, ecx
2:  cmp ecx, edx
    jae 3f
    lea r9d, [rcx + rdx]
    shr r9d, 1
    mov r10d, r9d
    shl r10d, 4
    cmp edi, [r8 + r10 + 4]
    jbe 21f
    lea ecx, [r9 + 1]
    jmp 2b
21: mov edx, r9d
    jmp 2b
3:  shl ecx, 4
    lea r9, [rip + fold_table_end]
    sub r9, r8
    cmp rcx, r9
    jae 9b
    mov edx, [r8 + rcx]
    cmp edi, edx
    jb 9b
    cmp dword ptr [r8 + rcx + 12], 0
    je 4f
    sub edx, edi
    test edx, 1
    jnz 9b
4:  add eax, [r8 + rcx + 8]
    ret

# fold_variants(cp) -> eax 1 when cp, a folded character of two bytes or more, and at most one other
# character fold to cp, with the first two bytes of each in dx and in edx's high half (cp's twice when
# it is alone); else 0. Uses rax, rcx, rdx, r8-r10
FN fold_variants
    mov r10d, -1                # the other character
    lea r8, [rip + fold_table]
    lea r9, [rip + fold_table_end]
1:  cmp r8, r9
    jae 3f
    mov eax, edi
    sub eax, [r8 + 8]
    cmp eax, [r8]
    jb 2f
    cmp eax, [r8 + 4]
    ja 2f
    cmp dword ptr [r8 + 12], 0
    je 11f
    mov ecx, eax
    sub ecx, [r8]
    test ecx, 1
    jnz 2f
11: cmp r10d, -1
    jne 8f                      # a third
    mov r10d, eax
2:  add r8, 16
    jmp 1b
3:  push rsi
    push rsi                    # room for an encoding
    mov rsi, rsp
    call utf8_encode
    movzx edx, word ptr [rsp]
    mov ecx, edx
    cmp r10d, -1
    je 4f
    push rdi
    mov edi, r10d
    lea rsi, [rsp + 8]
    call utf8_encode
    pop rdi
    movzx ecx, word ptr [rsp]
4:  shl ecx, 16
    or edx, ecx
    pop rsi
    pop rsi
    mov eax, 1
    ret
8:  xor eax, eax
    ret

'''

if __name__ == '__main__':
    main()
