#!/bin/sh
# usage: tools/gen-keysyms.sh keysymdef.h > src/plat/keysyms.s
# keysymdef.h comes from xorgproto (include/X11/keysymdef.h)
set -e
[ -f "$1" ] || { echo "usage: $0 keysymdef.h" >&2; exit 1; }
defs=$(mktemp)
ucs=$(mktemp)
trap 'rm -f "$defs" "$ucs"' EXIT
# name value [codepoint]
awk '/^#define XK_[A-Za-z0-9_]+[ \t]+0x[0-9a-fA-F]+/ {
    name = substr($2, 4); u = ""
    if (match($0, /U\+[0-9A-Fa-f]+/)) u = "0x" substr($0, RSTART + 2, RLENGTH - 2)
    print name, $3, u
}' "$1" > "$defs"
# keysym (decimal) value codepoint, for keysyms keysym_to_unicode cannot compute; first mapping wins
awk 'function hex(s,  i, v) { v = 0; s = tolower(substr(s, 3))
        for (i = 1; i <= length(s); i++) v = v * 16 + index("0123456789abcdef", substr(s, i, 1)) - 1
        return v }
    $3 != "" { v = hex($2); u = hex($3)
        if (u < 32 || (u >= 127 && u < 160)) next      # control keys are not text
        if (v > 255 && v < 16777216 && !(v in seen)) { seen[v] = 1; print v, $2, $3 } }' "$defs" > "$ucs"

cat <<'EOF'
# keysym names and keysym -> unicode, generated by tools/gen-keysyms.sh from xorgproto's keysymdef.h
.include "rhun.inc"
.section .rodata
.p2align 3
.globl keysym_names, keysym_names_count, keysym_ucs, keysym_ucs_count
EOF
printf 'keysym_names_count: .quad %d\n' "$(wc -l < "$defs")"
echo '# sorted by name (byte order): name, keysym'
echo 'keysym_names:'
LC_ALL=C sort -k1,1 "$defs" | awk '{ printf "    .quad .Lk%d\n    .long %s, 0\n", NR, $2 }'
printf 'keysym_ucs_count: .quad %d\n' "$(wc -l < "$ucs")"
echo '# sorted by keysym: keysym, codepoint'
echo 'keysym_ucs:'
sort -n -k1,1 "$ucs" | awk '{ printf "    .long %s, %s\n", $2, $3 }'
LC_ALL=C sort -k1,1 "$defs" | awk '{ printf ".Lk%d: .asciz \"%s\"\n", NR, $1 }'
