# Generated by tools/casefold.py from Unicode 16.0.0; do not edit.
# case_fold(cp) -> eax: the simple case folding of cp when it keeps its UTF-8 length, else cp
# (uses rax, rcx, rdx, r8-r10); fold_variants(cp) lists what folds to cp
.include "rhun.inc"

.text
FN case_fold
    mov eax, edi
    cmp edi, 0x80
    jae 1f
    lea ecx, [rdi - 'A']
    cmp ecx, 25
    ja 9f
    or eax, 0x20
9:  ret
    # the first range ending at or after cp
1:  lea r8, [rip + fold_table]
    lea rdx, [rip + fold_table_end]
    sub rdx, r8
    shr edx, 4
    xor ecx, ecx
2:  cmp ecx, edx
    jae 3f
    lea r9d, [rcx + rdx]
    shr r9d, 1
    mov r10d, r9d
    shl r10d, 4
    cmp edi, [r8 + r10 + 4]
    jbe 21f
    lea ecx, [r9 + 1]
    jmp 2b
21: mov edx, r9d
    jmp 2b
3:  shl ecx, 4
    lea r9, [rip + fold_table_end]
    sub r9, r8
    cmp rcx, r9
    jae 9b
    mov edx, [r8 + rcx]
    cmp edi, edx
    jb 9b
    cmp dword ptr [r8 + rcx + 12], 0
    je 4f
    sub edx, edi
    test edx, 1
    jnz 9b
4:  add eax, [r8 + rcx + 8]
    ret

# fold_variants(cp) -> eax 1 when cp, a folded character of two bytes or more, and at most one other
# character fold to cp, with the first two bytes of each in dx and in edx's high half (cp's twice when
# it is alone); else 0. Uses rax, rcx, rdx, r8-r10
FN fold_variants
    mov r10d, -1                # the other character
    lea r8, [rip + fold_table]
    lea r9, [rip + fold_table_end]
1:  cmp r8, r9
    jae 3f
    mov eax, edi
    sub eax, [r8 + 8]
    cmp eax, [r8]
    jb 2f
    cmp eax, [r8 + 4]
    ja 2f
    cmp dword ptr [r8 + 12], 0
    je 11f
    mov ecx, eax
    sub ecx, [r8]
    test ecx, 1
    jnz 2f
11: cmp r10d, -1
    jne 8f                      # a third
    mov r10d, eax
2:  add r8, 16
    jmp 1b
3:  push rsi
    push rsi                    # room for an encoding
    mov rsi, rsp
    call utf8_encode
    movzx edx, word ptr [rsp]
    mov ecx, edx
    cmp r10d, -1
    je 4f
    push rdi
    mov edi, r10d
    lea rsi, [rsp + 8]
    call utf8_encode
    pop rdi
    movzx ecx, word ptr [rsp]
4:  shl ecx, 16
    or edx, ecx
    pop rsi
    pop rsi
    mov eax, 1
    ret
8:  xor eax, eax
    ret

.section .rodata
.p2align 2
# lo, hi, delta, 1 when only lo, lo + 2, ... fold
fold_table:
    .long 0xb5, 0xb5, 775, 0
    .long 0xc0, 0xd6, 32, 0
    .long 0xd8, 0xde, 32, 0
    .long 0x100, 0x12e, 1, 1
    .long 0x132, 0x136, 1, 1
    .long 0x139, 0x147, 1, 1
    .long 0x14a, 0x176, 1, 1
    .long 0x178, 0x178, -121, 0
    .long 0x179, 0x17d, 1, 1
    .long 0x181, 0x181, 210, 0
    .long 0x182, 0x184, 1, 1
    .long 0x186, 0x186, 206, 0
    .long 0x187, 0x187, 1, 0
    .long 0x189, 0x18a, 205, 0
    .long 0x18b, 0x18b, 1, 0
    .long 0x18e, 0x18e, 79, 0
    .long 0x18f, 0x18f, 202, 0
    .long 0x190, 0x190, 203, 0
    .long 0x191, 0x191, 1, 0
    .long 0x193, 0x193, 205, 0
    .long 0x194, 0x194, 207, 0
    .long 0x196, 0x196, 211, 0
    .long 0x197, 0x197, 209, 0
    .long 0x198, 0x198, 1, 0
    .long 0x19c, 0x19c, 211, 0
    .long 0x19d, 0x19d, 213, 0
    .long 0x19f, 0x19f, 214, 0
    .long 0x1a0, 0x1a4, 1, 1
    .long 0x1a6, 0x1a6, 218, 0
    .long 0x1a7, 0x1a7, 1, 0
    .long 0x1a9, 0x1a9, 218, 0
    .long 0x1ac, 0x1ac, 1, 0
    .long 0x1ae, 0x1ae, 218, 0
    .long 0x1af, 0x1af, 1, 0
    .long 0x1b1, 0x1b2, 217, 0
    .long 0x1b3, 0x1b5, 1, 1
    .long 0x1b7, 0x1b7, 219, 0
    .long 0x1b8, 0x1b8, 1, 0
    .long 0x1bc, 0x1bc, 1, 0
    .long 0x1c4, 0x1c4, 2, 0
    .long 0x1c5, 0x1c5, 1, 0
    .long 0x1c7, 0x1c7, 2, 0
    .long 0x1c8, 0x1c8, 1, 0
    .long 0x1ca, 0x1ca, 2, 0
    .long 0x1cb, 0x1db, 1, 1
    .long 0x1de, 0x1ee, 1, 1
    .long 0x1f1, 0x1f1, 2, 0
    .long 0x1f2, 0x1f4, 1, 1
    .long 0x1f6, 0x1f6, -97, 0
    .long 0x1f7, 0x1f7, -56, 0
    .long 0x1f8, 0x21e, 1, 1
    .long 0x220, 0x220, -130, 0
    .long 0x222, 0x232, 1, 1
    .long 0x23b, 0x23b, 1, 0
    .long 0x23d, 0x23d, -163, 0
    .long 0x241, 0x241, 1, 0
    .long 0x243, 0x243, -195, 0
    .long 0x244, 0x244, 69, 0
    .long 0x245, 0x245, 71, 0
    .long 0x246, 0x24e, 1, 1
    .long 0x345, 0x345, 116, 0
    .long 0x370, 0x372, 1, 1
    .long 0x376, 0x376, 1, 0
    .long 0x37f, 0x37f, 116, 0
    .long 0x386, 0x386, 38, 0
    .long 0x388, 0x38a, 37, 0
    .long 0x38c, 0x38c, 64, 0
    .long 0x38e, 0x38f, 63, 0
    .long 0x391, 0x3a1, 32, 0
    .long 0x3a3, 0x3ab, 32, 0
    .long 0x3c2, 0x3c2, 1, 0
    .long 0x3cf, 0x3cf, 8, 0
    .long 0x3d0, 0x3d0, -30, 0
    .long 0x3d1, 0x3d1, -25, 0
    .long 0x3d5, 0x3d5, -15, 0
    .long 0x3d6, 0x3d6, -22, 0
    .long 0x3d8, 0x3ee, 1, 1
    .long 0x3f0, 0x3f0, -54, 0
    .long 0x3f1, 0x3f1, -48, 0
    .long 0x3f4, 0x3f4, -60, 0
    .long 0x3f5, 0x3f5, -64, 0
    .long 0x3f7, 0x3f7, 1, 0
    .long 0x3f9, 0x3f9, -7, 0
    .long 0x3fa, 0x3fa, 1, 0
    .long 0x3fd, 0x3ff, -130, 0
    .long 0x400, 0x40f, 80, 0
    .long 0x410, 0x42f, 32, 0
    .long 0x460, 0x480, 1, 1
    .long 0x48a, 0x4be, 1, 1
    .long 0x4c0, 0x4c0, 15, 0
    .long 0x4c1, 0x4cd, 1, 1
    .long 0x4d0, 0x52e, 1, 1
    .long 0x531, 0x556, 48, 0
    .long 0x10a0, 0x10c5, 7264, 0
    .long 0x10c7, 0x10c7, 7264, 0
    .long 0x10cd, 0x10cd, 7264, 0
    .long 0x13f8, 0x13fd, -8, 0
    .long 0x1c88, 0x1c88, 35267, 0
    .long 0x1c89, 0x1c89, 1, 0
    .long 0x1c90, 0x1cba, -3008, 0
    .long 0x1cbd, 0x1cbf, -3008, 0
    .long 0x1e00, 0x1e94, 1, 1
    .long 0x1e9b, 0x1e9b, -58, 0
    .long 0x1ea0, 0x1efe, 1, 1
    .long 0x1f08, 0x1f0f, -8, 0
    .long 0x1f18, 0x1f1d, -8, 0
    .long 0x1f28, 0x1f2f, -8, 0
    .long 0x1f38, 0x1f3f, -8, 0
    .long 0x1f48, 0x1f4d, -8, 0
    .long 0x1f59, 0x1f59, -8, 0
    .long 0x1f5b, 0x1f5b, -8, 0
    .long 0x1f5d, 0x1f5d, -8, 0
    .long 0x1f5f, 0x1f5f, -8, 0
    .long 0x1f68, 0x1f6f, -8, 0
    .long 0x1f88, 0x1f8f, -8, 0
    .long 0x1f98, 0x1f9f, -8, 0
    .long 0x1fa8, 0x1faf, -8, 0
    .long 0x1fb8, 0x1fb9, -8, 0
    .long 0x1fba, 0x1fbb, -74, 0
    .long 0x1fbc, 0x1fbc, -9, 0
    .long 0x1fc8, 0x1fcb, -86, 0
    .long 0x1fcc, 0x1fcc, -9, 0
    .long 0x1fd8, 0x1fd9, -8, 0
    .long 0x1fda, 0x1fdb, -100, 0
    .long 0x1fe8, 0x1fe9, -8, 0
    .long 0x1fea, 0x1feb, -112, 0
    .long 0x1fec, 0x1fec, -7, 0
    .long 0x1ff8, 0x1ff9, -128, 0
    .long 0x1ffa, 0x1ffb, -126, 0
    .long 0x1ffc, 0x1ffc, -9, 0
    .long 0x2132, 0x2132, 28, 0
    .long 0x2160, 0x216f, 16, 0
    .long 0x2183, 0x2183, 1, 0
    .long 0x24b6, 0x24cf, 26, 0
    .long 0x2c00, 0x2c2f, 48, 0
    .long 0x2c60, 0x2c60, 1, 0
    .long 0x2c63, 0x2c63, -3814, 0
    .long 0x2c67, 0x2c6b, 1, 1
    .long 0x2c72, 0x2c72, 1, 0
    .long 0x2c75, 0x2c75, 1, 0
    .long 0x2c80, 0x2ce2, 1, 1
    .long 0x2ceb, 0x2ced, 1, 1
    .long 0x2cf2, 0x2cf2, 1, 0
    .long 0xa640, 0xa66c, 1, 1
    .long 0xa680, 0xa69a, 1, 1
    .long 0xa722, 0xa72e, 1, 1
    .long 0xa732, 0xa76e, 1, 1
    .long 0xa779, 0xa77b, 1, 1
    .long 0xa77d, 0xa77d, -35332, 0
    .long 0xa77e, 0xa786, 1, 1
    .long 0xa78b, 0xa78b, 1, 0
    .long 0xa790, 0xa792, 1, 1
    .long 0xa796, 0xa7a8, 1, 1
    .long 0xa7b3, 0xa7b3, 928, 0
    .long 0xa7b4, 0xa7c2, 1, 1
    .long 0xa7c4, 0xa7c4, -48, 0
    .long 0xa7c6, 0xa7c6, -35384, 0
    .long 0xa7c7, 0xa7c9, 1, 1
    .long 0xa7cc, 0xa7cc, 1, 0
    .long 0xa7d0, 0xa7d0, 1, 0
    .long 0xa7d6, 0xa7da, 1, 1
    .long 0xa7f5, 0xa7f5, 1, 0
    .long 0xab70, 0xabbf, -38864, 0
    .long 0xff21, 0xff3a, 32, 0
    .long 0x10400, 0x10427, 40, 0
    .long 0x104b0, 0x104d3, 40, 0
    .long 0x10570, 0x1057a, 39, 0
    .long 0x1057c, 0x1058a, 39, 0
    .long 0x1058c, 0x10592, 39, 0
    .long 0x10594, 0x10595, 39, 0
    .long 0x10c80, 0x10cb2, 64, 0
    .long 0x10d50, 0x10d65, 32, 0
    .long 0x118a0, 0x118bf, 32, 0
    .long 0x16e40, 0x16e5f, 32, 0
    .long 0x1e900, 0x1e921, 34, 0
fold_table_end:
